name: Run tests
on:
  pull_request:
    branches:
    - master
jobs:

  run-tests:
  
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
      
    - name: Setup and execute Gradle 'test' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
        
    - name: Generate test report
      uses: dorny/test-reporter@v1
      with:
        name: test-results         
        path: build/test-results/test/TEST-*.xml
        reporter: java-junit
        fail-on-error: true
